---
askpass_program_path: "{{ playbook_dir }}/bin/mac-askpass.sh"
configure_dotfiles: true
configure_terminal: false
configure_macos: true
install_mas_apps: true
configure_pam_touchid: true
configure_homebrew: true
configure_dock: true
configure_gpg: true
configure_sudoers: false
configure_sublime: false

# Specify overrides in config.yaml
user:
  name: ""
  email: "" # email address used for WKD key lookup
  gpg_key: ""

chezmoi_dotfiles_repo: ""

macos:
  hostname: "{{ user.name }}s-mac"
  measurement_units: "Inches"
  Screenshots:
    folder: "{{ lookup('env', 'HOME') }}/Pictures/Screenshots/unsorted"
  Finder:
    AppleShowAllFiles: true
    ShowPathbar: true
    ShowStatusBar: true
    _FXShowPosixPathInTitle: true
  Dock:
    autohide: true
    minimizeToApplication: false
    tilesize: 64
  AutomaticSpellingCorrectionEnabled: true
  enableFirewall: false
  enableStealthMode: false
  enableSsh: false

gpg_keyserver: keys.openpgp.org

# From which repository should we install homebrew?
homebrew_repository: https://github.com/Homebrew/brew

# Set to true if you want to use master branch instead of release auto-detect,
# or you use custom fork specified in homebrew_repository
homebrew_repository_use_master: false

# How much times to retry, if installation of package / tap / cask fails ?
# This can happen during network problems.
homebrew_retries: 5

# Delay between each retry attempt.
homebrew_delay: 3
homebrew_cask_appdir: /Applications
# If set to true, passes --greedy to brew cask outdated when checking if an installed cask has a newer version available.
homebrew_cask_greedy_mode: true

sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/amatos/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_repo_version: main # Replace with your default branch
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .macos
  - .vimrc

macos_script: "{{ playbook_dir }}/bin/customize_macos.sh --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "Theme - Cobalt2"
  - "TrailingSpaces"
  - "WordingStatus"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
