---
dock_dockutil_install: true

dock_dockitems:
  - label: "Apps"
    path: "/System/Applications/Apps.app/"
    action: add
    position: 1
  - label: "Safari"
    path: "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/"
    action: add
    position: 2
  - label: "Helium"
    path: "/Applications/Helium.app/"
    action: add
    position: 3
  - label: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    action: add
    position: 4
  - label: "Mail"
    path: "/System/Applications/Mail.app/"
    action: add
    position: 5
  - label: "Messages"
    path: "/System/Applications/Messages.app/"
    action: add
    position: 6
  - label: "Phone"
    path: "/System/Applications/Phone.app/"
    action: add
    position: 7
  - label: "FaceTime"
    path: "/System/Applications/FaceTime.app/"
    action: add
    position: 8
  - label: "Calendar"
    path: "/System/Applications/Calendar.app/"
    action: add
    position: 9
  - label: "Contacts"
    path: "/System/Applications/Contacts.app/"
    action: add
    position: 10
  - label: "News"
    path: "/System/Applications/News.app/"
    action: add
    position: 11
  - label: "Music"
    path: "/System/Applications/Music.app/"
    action: add
    position: 12
  - label: "Photos"
    path: "/System/Applications/Photos.app/"
    action: add
    position: 13
  - label: "TV"
    path: "/System/Applications/TV.app/"
    action: add
    position: 14
  - label: "App Store"
    path: "/System/Applications/App Store.app/"
    action: add
    position: 15
  - label: "System Settings"
    path: "/System/Applications/System Settings.app/"
    action: add
    position: 16
  - label: "Preview"
    path: "/System/Applications/Preview.app/"
    action: add
    position: 17
  - label: "Zed"
    path: "/Applications/Zed.app/"
    action: add
    position: 18
  - label: "Ghostty"
    path: "/Applications/Ghostty.app/"
    action: add
    position: 19
  - label: "Claude"
    path: "/Applications/Claude.app/"
    action: add
    position: 20
  - label: Reminders
    action: remove
    allhomes: true
  - label: Notes
    action: remove
    allhomes: true
  - label: Games
    action: remove
    allhomes: true
  - label: Maps
    action: remove
    allhomes: true
