---
dockutil_install: true
dockitems_remove: []
  # - Launchpad
  # - TV
  # - Podcasts
  # - "App Store"
dockitems_persist:
  - name: "Apps"
    path: "/System/Applications/Apps.app/"
    pos: 1
  - name: "Safari"
    path: "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/"
    pos: 2
  - name: "Helium"
    path: "/Applications/Helium.app/"
    pos: 3
  - name: "Mail"
    path: "/System/Applications/Mail.app/"
    pos: 4
  - name: "Messages"
    path: "/System/Applications/Messages.app/"
    pos: 5
  - name: "Phone"
    path: "/System/Applications/Phone.app/"
    pos: 6
  - name: "FaceTime"
    path: "/System/Applications/FaceTime.app/"
    pos: 7
  - name: "Fantastical"
    path: "/Applications/Fantastical.app/"
    pos: 8
  - name: "Contacts"
    path: "/System/Applications/Contacts.app/"
    pos: 9
  - name: "News"
    path: "/System/Applications/News.app/"
    pos: 10
  - name: "Music"
    path: "/System/Applications/Music.app/"
    pos: 11
  - name: "Photos"
    path: "/System/Applications/Photos.app/"
    pos: 12
  - name: "iPhone Mirroring"
    path: "/System/Applications/iPhone Mirroring.app/"
    pos: 13
  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 14
  - name: "Preview"
    path: "/System/Applications/Preview.app/"
    pos: 15
  - name: "Zed"
    path: "/Applications/Zed.app/"
    pos: 16
  - name: "Ghostty"
    path: "/Applications/Ghostty.app/"
    pos: 17
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5
