---
dockutil_install: true
dockitems_remove:
  - Calendar
  - Reminders
  - Notes
  - Games
  - Maps
dockitems_persist:
  - name: "Apps"
    path: "/System/Applications/Apps.app/"
    pos: 1
  - name: "Safari"
    path: "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/"
    pos: 2
  - name: "Helium"
    path: "/Applications/Helium.app/"
    pos: 3
  - name: "Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 4
  - name: "Mail"
    path: "/System/Applications/Mail.app/"
    pos: 5
  - name: "Messages"
    path: "/System/Applications/Messages.app/"
    pos: 6
  - name: "Phone"
    path: "/System/Applications/Phone.app/"
    pos: 7
  - name: "FaceTime"
    path: "/System/Applications/FaceTime.app/"
    pos: 8
  - name: "Fantastical"
    path: "/System/Applications/Calendar.app/"
    pos: 9
  - name: "Contacts"
    path: "/System/Applications/Contacts.app/"
    pos: 10
  - name: "News"
    path: "/System/Applications/News.app/"
    pos: 11
  - name: "Music"
    path: "/System/Applications/Music.app/"
    pos: 12
  - name: "Photos"
    path: "/System/Applications/Photos.app/"
    pos: 13
  - name: "TV"
    path: "/System/Applications/TV.app/"
    pos: 14
  - name: "App Store"
    path: "/System/Applications/App Store.app/"
    pos: 15
  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 16
  - name: "Preview"
    path: "/System/Applications/Preview.app/"
    pos: 17
  - name: "Zed"
    path: "/Applications/Zed.app/"
    pos: 18
  - name: "Ghostty"
    path: "/Applications/Ghostty.app/"
    pos: 19
  - name: "Claude"
    path: "/Applications/Claude.app/"
    pos: 20
  - name: "Siri"
    path: "/System/Applications/Campo.app/"
    pos: 21
